### ISSUE TITLE
Adds an icon to differenciate Figma Views 

### ISSUE THREAD

**Issue by netonjm** [microsoft/FigmaSharp#199]
Figma generated views can be moved in the project, and sometimes when they are in the same directory like other views it is not easy to differentiate.

It would be very useful include a overlay to make clear which are FigmaSharp views. Additionally we could add some sync/unsynch color, because when a file is generated, sometimes because the document changes or a layout name changes can be un synch, and this causes the developer not to understand why this happens.

Red icon color means the element is out of sync/ Green in synch

![image](https://user-images.githubusercontent.com/1587480/79590814-e6febe80-80d7-11ea-93f5-e11d11c2fe7c.png)

Something similar to this

**Comment by vancura** [comment]
Yup. I will be on it. Not now, but I will :)

**Comment by hbons** [comment]
so....I'm not sure if this needs a special icon. it's still C# source code, and we don't want to overwhelm users with too many file types. The .designer.cs file _is_ special though, so we could have a new icon for that.

**Comment by vancura** [comment]
Yup, that’s what I thought. I don’t want to introduce more overlays, but a filetype icon makes sense. Although we already have one, don’t we.

**Comment by netonjm** [comment]
I’m ok with any approach to make this file distinguish somehow 🥰
