### ISSUE TITLE
Package Figma styles into projects

### ISSUE THREAD

**Issue by netonjm** [microsoft/FigmaSharp#215]
Finish the implementation of:
https://github.com/netonjm/FigmaSharp/commit/079979e9115f9c0276a637fbc638c252956ea1cc#diff-1ec38ae03391eaee209e3389301ecbf0

**Comment by hbons** [comment]
in #234.

**Comment by netonjm** [comment]
This will close automatically when merged in master

**Comment by netonjm** [comment]
This will close automatically when merged in master

**Comment by netonjm** [comment]
Current implementation doesn't work with FigmaSharp Core Library
revive : #231
