### ISSUE TITLE
Custom containers create NSWindow instead of NSView

### ISSUE THREAD

**Issue by hbons** [microsoft/FigmaSharp#220]
File: https://www.figma.com/file/ht2voRXaqsBKIwzkv6jrAD/Untitled?node-id=0%3A1

result: 
<img width="667" alt="image" src="https://user-images.githubusercontent.com/103326/81739183-2b913600-949b-11ea-9a40-84ffbb83f722.png">
<img width="688" alt="image" src="https://user-images.githubusercontent.com/103326/81739208-351a9e00-949b-11ea-8af6-f05b753ab22f.png">
<img width="690" alt="image" src="https://user-images.githubusercontent.com/103326/81739240-4499e700-949b-11ea-9afb-a7999365f25e.png">

Expected result:
	public partial class TestClass : AppKit.NSView
	public partial class SubClass : TestClass
	public partial class SubClass2 : TestClass

**Comment by netonjm** [comment]
The expected result it's correct, why you want to generate 3 windows here?

**Comment by netonjm** [comment]
I just read wrong good catch!
