### ISSUE TITLE
Don't generate this property value (items or text) in code generation

### ISSUE THREAD

**Issue by netonjm** [microsoft/FigmaSharp#236]
Sometimes designers need to add some mockup values in the current design to check the text and font is correct etc... 
When we convert this design into real code, sometimes we need to override this value, or remove it from the design

To make this more easy it would be great to include it a simple flag after the layername to (mostly TextLayers or ComboItems) to avoid create it.

This already exists in Wpf and it's represented by :
 xmlns:dvm="clr-namespace:Dima.Controls.DesignViewModel"
 d:DataContext ="{d:DesignInstance {x:Type dvm:ProgressReportSample1}, IsDesignTimeCreatable=True}"

**Comment by hbons** [comment]
let's use the same "//" or "#" and apply them to text objects.

**Comment by netonjm** [comment]
sounds good
