### ISSUE TITLE
document styles are missing from API FigmaFrame

### ISSUE THREAD

**Issue by blacroixSP** [microsoft/FigmaSharp#364]
`FigmaFrame` loses its link to the styles with deserialization.

This make out-of-figma style customization a nightmare (like in-app choice of theme colors / font).

The styles ids should at least be saved for post deserialization processing.

**Comment by netonjm** [comment]
Good catch! Do you have some easy sample to try and test the issue? I can spend some time to take a look or if you want to contribute it will be a pleasure to review it!

**Comment by blacroixSP** [comment]
I can check to do a quick merge request and elaborate from there.

**Comment by blacroixSP** [comment]
found the styles used in Vector at some point, I used the same structure for that in the PR.

can check with a simple design [here](https://www.figma.com/file/ildy6idaILqA6EYvu6JGbr/Test_Styles).

**Comment by netonjm** [comment]
this is perfect thank you!
